#!/bin/ksh

sed -E 's/^(username|password)=.*/\1=XXX/;s/(\.[a-z]+){2,}/.DOM.AIN/' gs1900powerHA.cf > gs1900powerHA-dist.cf
install -m 0755 -o daemon -g daemon gs1900powerHA.py /usr/local/bin
install -m 0400 -o daemon -g daemon gs1900powerHA.cf /usr/local/etc
install -m 0644 -o daemon -g daemon gs1900powerHA.service /etc/systemd/system
systemctl enable gs1900powerHA.service
systemctl start gs1900powerHA.service


